repos:
- repo: https://github.com/psf/black
  rev: 21.4b2
  hooks:
  - id: black
    # default black line length is 88
    args: [--target-version=py35, --line-length=79]
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.1
  hooks:
  - id: flake8
    # default flake8 line length is 79
