---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }} and Gradle
        uses: ome/action-gradle@v3.2
        with:
          java-version: ${{ matrix.java }}
      - name: Prepare minio
        run: |
          (cd ci && ./startminio.sh)
          echo AWS_ACCESS_KEY_ID=stsadmin >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY=stsadmin-secret >> $GITHUB_ENV
      - name: Build
        run: |
          gradle check -PexcludeTests="**/s3*" 
          gradle shadowJar
